// seeds/seedPages.ts
// Seed script to populate the pages table with initial data
import { db } from "@/drizzle/db";
import { pages } from "@/drizzle/schema";

export async function migratePagesData() {
  try {
    // Insert main pages data
    const mainPages = await db.insert(pages).values([
      { name: "L'école", slug: "l-ecole", order: 1, link: "#" },
      { name: "Programmes", slug: "programmes", order: 2, link: "#" },
      { name: "Bibliothèque numérique", slug: "bibliotheque-numerique", order: 3, link: "https://promo-ci.youscribe.com/pysci/lp_service_gen?utm_source=youscribe&utm_medium=others&utm_campaign=HP" },
      { name: "E-Learning", slug: "e-learning", order: 4, link: "https://myschool.atlantique-ibs.net/" },
    ]).returning();

    // Insert sub-pages data (linked to main pages)
    await db.insert(pages).values([
      // Sub-pages for mainPage "L"école"
      { name: "Découvrez AIBS", slug: "decouvrez-aibs", parentId: mainPages.find(page => page.order === 1)?.id, order: 1 },
      { name: "Système Qualité", slug: "systeme-qualite", parentId: mainPages.find(page => page.order === 1)?.id, order: 2 },
      { name: "Demande de Document", slug: "demande-de-document", parentId: mainPages.find(page => page.order === 1)?.id, order: 3, content: "Contenu pour demande de document" },
      { name: "Demande de Vacation", slug: "demande-de-vacation", parentId: mainPages.find(page => page.order === 1)?.id, order: 4, content: "Contenu pour demande de vacation" },
      { name: "Demande de Stagiaire", slug: "demande-de-stagiaire", parentId: mainPages.find(page => page.order === 1)?.id, order: 5, content: "Contenu pour demande de stagiaire" },

      // Sub-pages for "Découvrez AIBS"
      { name: "Mot du PDG", slug: "mot-du-pdg", parentId: mainPages.find(page => page.name === "Découvrez AIBS")?.id, order: 1, cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg" },
      { name: "Présentation", slug: "presentation", parentId: mainPages.find(page => page.name === "Découvrez AIBS")?.id, order: 2, cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg" },
      { name: "Points Forts", slug: "points-forts", parentId: mainPages.find(page => page.name === "Découvrez AIBS")?.id, order: 3, cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg" },
      // Sub-pages for "Système Qualité"
      { name: "Notre Politique Qualité", slug: "notre-politique-qualite", parentId: mainPages.find(page => page.name === "Système Qualité")?.id, order: 1, cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg" },
      { name: "Satisfaction Client", slug: "satisfaction-client", parentId: mainPages.find(page => page.name === "Système Qualité")?.id, order: 2, cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg" },

      // Sub-pages for mainPage "Programmes"
      { parentId: mainPages.find(page => page.order === 2)?.id, order: 1, level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Brevet de Technicien Supérieur (BTS)", slug: "bts", duration: "2 ans", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bts.jpg" },
      { parentId: mainPages.find(page => page.order === 2)?.id, order: 2, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", professionnalisation: "Stage garanti", internationalisation: "Séjour linguistique + visa France", name: "Bachelor", slug: "bachelor", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bachelor.jpg" },
      { parentId: mainPages.find(page => page.order === 2)?.id, order: 3, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", professionnalisation: "Stage garanti sur les 3 ans", name: "Licence de Droit", slug: "licence-de-droit", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-droit.jpg" },
      { parentId: mainPages.find(page => page.order === 2)?.id, order: 4, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Licence Professionnelle", slug: "licence-professionnelle", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-pro.jpg" },
      { parentId: mainPages.find(page => page.order === 2)?.id, order: 5, level: "Bac +4", campus: "Cocody Danga", langue: "Français", rythm: "Cours en ligne", name: "Master Professionnel", slug: "master-professionnel", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_master-pro.jpg" },
      { parentId: mainPages.find(page => page.order === 2)?.id, order: 6, level: "Bac +5", campus: "Cocody Danga", langue: "Français", rythm: "Cours en ligne", name: "MBA", slug: "mba", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_mba.jpg" },
      { parentId: mainPages.find(page => page.order === 2)?.id, order: 7, name: "Bourse d'étude en Chine", slug: "bourse-detude-en-chine", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_vap-vae.jpg" },
      { parentId: mainPages.find(page => page.order === 2)?.id, order: 8, level: "Bac +3 / Bac +5", campus: "Cocody Danga", langue: "Français", rythm: "Cours du jour / Cours en ligne", name: "VAE / VAP", slug: "vae-vap", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_vap-vae.jpg" },

      // Sub-pages for "Brevet de Technicien Supérieur (BTS) - DONE. TO CONTINUE WITH OTHER PROGRAMS"
      { parentId: mainPages.find(page => page.name === "Brevet de Technicien Supérieur (BTS)")?.id, order: 1, level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", professionnalisation: "Stage garanti", internationalisation: "Séjour linguistique + visa France", name: "BTS Gestion Commerciale", slug: "bts-gestion-commerciale", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", content: "Content for bts-gestion-commerciale" },
      { parentId: mainPages.find(page => page.name === "Brevet de Technicien Supérieur (BTS)")?.id, order: 2, level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", professionnalisation: "Stage garanti", name: "BTS Finance Comptabilité & Gestion d'Entreprises", slug: "bts-finance-comptabilite-gestion-dentreprises", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", content: "Content for bts-finance-comptabilite-gestion-dentreprises" },
      { parentId: mainPages.find(page => page.name === "Brevet de Technicien Supérieur (BTS)")?.id, order: 3, level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", professionnalisation: "Stage garanti", name: "BTS Informatique: Développeur d'Application", slug: "bts-informatique-developpeur-dapplication", duration: "2 ans", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", content: "Content for bts-informatique-developpeur-dapplication" },
      { parentId: mainPages.find(page => page.name === "Brevet de Technicien Supérieur (BTS)")?.id, order: 4, level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", professionnalisation: "Stage garanti", name: "BTS Ressources Humaines & Communication", slug: "bts-ressources-humaines-communication", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", content: "Content for bts-ressources-humaines-communication" },
      { parentId: mainPages.find(page => page.name === "Brevet de Technicien Supérieur (BTS)")?.id, order: 5, level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", professionnalisation: "Stage garanti", name: "BTS Transport & Logistique", slug: "bts-transport-logistique", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", content: "Content for bts-transport-logistique" },
      // Sub-pages for "Licence Pro"
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 1, level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Brevet de Technicien Supérieur (BTS)", slug: "bts", duration: "2 ans", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bts.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 2, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", professionnalisation: "Stage garanti", internationalisation: "Séjour linguistique + visa France", name: "Bachelor", slug: "bachelor", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bachelor.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 3, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", professionnalisation: "Stage garanti sur les 3 ans", name: "Licence de Droit", slug: "licence-de-droit", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-droit.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 4, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Licence Professionnelle", slug: "licence-professionnelle", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-pro.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 5, level: "Bac +4", campus: "Cocody Danga", langue: "Français", rythm: "Cours en ligne", name: "Master Professionnel", slug: "master-professionnel", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_master-pro.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 6, level: "Bac +5", campus: "Cocody Danga", langue: "Français", rythm: "Cours en ligne", name: "MBA", slug: "mba", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_mba.jpg" },
      // Sub-pages for "Master Pro"
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 1, level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Brevet de Technicien Supérieur (BTS)", slug: "bts", duration: "2 ans", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bts.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 2, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", professionnalisation: "Stage garanti", internationalisation: "Séjour linguistique + visa France", name: "Bachelor", slug: "bachelor", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bachelor.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 3, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", professionnalisation: "Stage garanti sur les 3 ans", name: "Licence de Droit", slug: "licence-de-droit", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-droit.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 4, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Licence Professionnelle", slug: "licence-professionnelle", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-pro.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 5, level: "Bac +4", campus: "Cocody Danga", langue: "Français", rythm: "Cours en ligne", name: "Master Professionnel", slug: "master-professionnel", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_master-pro.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 6, level: "Bac +5", campus: "Cocody Danga", langue: "Français", rythm: "Cours en ligne", name: "MBA", slug: "mba", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_mba.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 7, name: "Bourse d'étude en Chine", slug: "bourse-detude-en-chine", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_vap-vae.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 8, level: "Bac +3 / Bac +5", campus: "Cocody Danga", langue: "Français", rythm: "Cours du jour / Cours en ligne", name: "VAE / VAP", slug: "vae-vap", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_vap-vae.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 8, level: "Bac +3 / Bac +5", campus: "Cocody Danga", langue: "Français", rythm: "Cours du jour / Cours en ligne", name: "VAE / VAP", slug: "vae-vap", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_vap-vae.jpg" },
      // Sub-pages for "MBA"
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 1, level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Brevet de Technicien Supérieur (BTS)", slug: "bts", duration: "2 ans", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bts.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 2, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", professionnalisation: "Stage garanti", internationalisation: "Séjour linguistique + visa France", name: "Bachelor", slug: "bachelor", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bachelor.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 3, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", professionnalisation: "Stage garanti sur les 3 ans", name: "Licence de Droit", slug: "licence-de-droit", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-droit.jpg" },
      { parentId: mainPages.find(page => page.name === "2")?.id, order: 4, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Licence Professionnelle", slug: "licence-professionnelle", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-pro.jpg" },
      // Sub-pages for "VAE / VAP"
      { parentId: mainPages.find(page => page.name === "VAE / VAP")?.id, order: 1, content:"", name: "VAE / VAP", slug: "vae-vap", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg" },
    ]);

    console.log("✅ Pages data migration completed successfully!");
  } catch (error) {
    console.error("❌ Pages data migration failed:", error);
  }
}