// seeds/seedPrograms.ts
// Seed script to populate the programs table with initial data
import { db } from "@/drizzle/db";
import { programs } from "@/drizzle/schema";

export async function migrateProgramsData() {
  try {
    // Insert main programs
    const mainPrograms = await db.insert(programs).values([
    { name: 'Brevet de Technicien Supérieur (BTS)', slug: 'bts', description: 'Programme de deux ans menant au diplôme de BTS.', level: 'Bac +2', campus: 'Cocody Danga', langue: 'Français', duration: '2 ans', thumbnail: 'https://atlantique-ibs.net/media/uploads/vignettes/_bts.jpg', cover: 'https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg', order: 1 },
    { name: 'Bachelor', slug: 'bachelor', description: '', level: 'Bac +3', campus: 'Cocody Danga', langue: 'Français', rythm: 'Formation initiale', thumbnail: 'https://atlantique-ibs.net/media/uploads/vignettes/_bachelor.jpg', cover: 'https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg', order: 2 },
    { name: 'Licence de Droit', slug: 'licence-de-droit', description: '', level: 'Bac +3', campus: 'Cocody Danga', langue: 'Français', rythm: 'Formation initiale', thumbnail: 'https://atlantique-ibs.net/media/uploads/vignettes/_licence-droit.jpg', cover: 'https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg', order: 3 },
    { name: 'Licence Professionnelle', slug: 'licence-professionnelle', description: '', level: 'Bac +3', campus: 'Cocody Danga', langue: 'Français', rythm: 'Formation initiale', thumbnail: 'https://atlantique-ibs.net/media/uploads/vignettes/_licence-pro.jpg', cover: 'https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg', order: 4 },
    { name: 'Bourse d\'étude en Chine', slug: 'bourse-detude-en-chine', description: '', level: "", campus: "", langue: 'Français', rythm: 'Formation initiale', thumbnail: 'https://atlantique-ibs.net/media/uploads/vignettes/_b-e-c.jpg', cover: 'https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg', order: 5 },
    { name: 'Master Professionnel', slug: 'master-professionnel', description: '', level: 'Bac +4', campus: 'Cocody Danga', langue: 'Français', rythm: 'Formation initiale', thumbnail: 'https://atlantique-ibs.net/media/uploads/vignettes/_master-pro.jpg', cover: 'https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg', order: 6 },
    { name: 'MBA', slug: 'mba', description: '', level: 'Bac +5', campus: 'Cocody Danga', langue: 'Français', rythm: 'Formation initiale', thumbnail: 'https://atlantique-ibs.net/media/uploads/vignettes/_mba.jpg', cover: 'https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg', order: 7 },
    { name: 'VAE / VAP', slug: 'vae-vap', description: '', level: 'Bac +3 / Bac +5', campus: 'Cocody Danga', langue: 'Français', rythm: 'Formation initiale', thumbnail: 'https://atlantique-ibs.net/media/uploads/vignettes/_vap-vae.jpg', cover: 'https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg', order: 8 },
  ]).returning();

  // Insert sub-programs (linked to main programs)
  await db.insert(programs).values([
    // Sub-programs for BTS
    { parentId: mainPrograms.find(p => p.name === "Brevet de Technicien Supérieur (BTS)")?.id, name: 'BTS Gestion Commerciale', slug: 'bts-gestion-commerciale', description: "", level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", duration: '3 ans', cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", order: 1 },
    { parentId: mainPrograms.find(p => p.name === "Brevet de Technicien Supérieur (BTS)")?.id, name: 'BTS Finance Comptabilité & Gestion d\'Entreprises', slug: 'bts-finance-comptabilite-gestion-dentreprises', description: "", level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", duration: '3 ans', cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", order: 2 },
    { parentId: mainPrograms.find(p => p.name === "Brevet de Technicien Supérieur (BTS)")?.id, name: "BTS Informatique: Développeur d'Application", slug: "bts-informatique-developpeur-dapplication", description: "", level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", duration: "", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", order: 3 },
    { parentId: mainPrograms.find(p => p.name === "Brevet de Technicien Supérieur (BTS)")?.id, name: "BTS Ressources Humaines & Communication", slug: "bts-ressources-humaines-communication", description: "", level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", duration: "", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", order: 4 },
    { parentId: mainPrograms.find(p => p.name === "Brevet de Technicien Supérieur (BTS)")?.id, name: "BTS Transport & Logistique", slug: "bts-transport-logistique", description: "", level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", duration: "", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", order: 5 },
    // Sub-programs for "Licence Pro"
    { parentId: mainPrograms.find(p => p.name === "Licence Professionnelle")?.id, order: 1, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Audit & Contrôle de Gestion", slug: "audit-controle-de-gestion", duration: "2 ans", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bts.jpg" },
    { parentId: mainPrograms.find(p => p.name === "Licence Professionnelle")?.id, order: 2, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Banque & Assurance", slug: "banque-assurance", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bachelor.jpg" },
    { parentId: mainPrograms.find(p => p.name === "Licence Professionnelle")?.id, order: 3, level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Gestion des Ressources Humaines", slug: "gestion-des-ressources-humaines", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-droit.jpg" },
    { parentId: mainPrograms.find(p => p.name === "Licence Professionnelle")?.id, order: 4, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Informatique", slug: "informatique", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-pro.jpg" },
    { parentId: mainPrograms.find(p => p.name === "Licence Professionnelle")?.id, order: 5, level: "Bac +3", campus: "Cocody Danga", langue: "Français", rythm: "Cours en ligne", name: "Transport - Logistique", slug: "transport-logistique", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_master-pro.jpg" },
    { parentId: mainPrograms.find(p => p.name === "Licence Professionnelle")?.id, order: 6, level: "Bac +2", campus: "Cocody Danga", langue: "Français", rythm: "Cours en ligne", name: "Marketing - Management", slug: "marketing-management", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_mba.jpg" },
    // Sub-programs for "Master Pro"
    { parentId: mainPrograms.find(p => p.name === "Master Professionnel")?.id, order: 1, level: "Bac +5", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Achats & Approvisionnements", slug: "achats-approvisionnements", duration: "2 ans", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bts.jpg" },
    { parentId: mainPrograms.find(p => p.name === "Master Professionnel")?.id, order: 2, level: "Bac +5", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Audit & Finance d'Entreprise", slug: "audit-finance-dentreprise", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bachelor.jpg" },
    { parentId: mainPrograms.find(p => p.name === "Master Professionnel")?.id, order: 3, level: "", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Management des Projets et de l'Innovation", slug: "management-des-projets-et-de-linnovation", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-droit.jpg" },
    { parentId: mainPrograms.find(p => p.name === "Master Professionnel")?.id, order: 4, level: "", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Management des Ressources Humaines", slug: "management-des-ressources-humaines", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-pro.jpg" },
    { parentId: mainPrograms.find(p => p.name === "Master Professionnel")?.id, order: 5, level: "", campus: "Cocody Danga", langue: "Français", rythm: "Cours en ligne", name: "Management des Systèmes d'Informations", slug: "management-des-systemes-dinformations", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_master-pro.jpg" },
    { parentId: mainPrograms.find(p => p.name === "Master Professionnel")?.id, order: 6, level: "", campus: "Cocody Danga", langue: "Français", rythm: "Cours en ligne", name: "Management Opérationnel et Stratégique", slug: "management-operationnel-et-strategique", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_mba.jpg" },
    { parentId: mainPrograms.find(p => p.name === "Master Professionnel")?.id, order: 7, level: "", name: "Marketing & Stratégie Digitale", slug: "marketing-strategie-digitale", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_vap-vae.jpg" },
    { parentId: mainPrograms.find(p => p.name === "Master Professionnel")?.id, order: 8, level: "", campus: "Cocody Danga", langue: "Français", rythm: "Cours du jour / Cours en ligne", name: "Supply Chain Management", slug: "supply-chain-management", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_vap-vae.jpg" },
    { parentId: mainPrograms.find(p => p.name === "Master Professionnel")?.id, order: 8, level: "Bac +4", campus: "Cocody Danga", langue: "Français", rythm: "Cours du jour / Cours en ligne", name: "Contrôle de Gestion et Audit Organisationnel", slug: "controle-de-gestion-et-audit-organisationnel", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_vap-vae.jpg" },
    // Sub-programs for "MBA"
    { parentId: mainPrograms.find(p => p.name === "MBA")?.id, order: 1, level: "Bac +5", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "Global MBA", slug: "global-mba", duration: "2 ans", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bts.jpg" },
    { parentId: mainPrograms.find(p => p.name === "MBA")?.id, order: 2, level: "Bac +5", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "MBA Santé Sécurité Environnement", slug: "mba-sante-securite-environnement", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_bachelor.jpg" },
    { parentId: mainPrograms.find(p => p.name === "MBA")?.id, order: 3, level: "Bac +5", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "MBA Data Science & Intelligence Artificielle", slug: "mba-data-science-intelligence-artificielle", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-droit.jpg" },
    { parentId: mainPrograms.find(p => p.name === "MBA")?.id, order: 4, level: "Bac +5", campus: "Cocody Danga", langue: "Français", rythm: "Formation initiale", name: "MBA Management des Ressources Humaines", slug: "mba-management-des-ressources-humaines", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg", thumbnail: "https://atlantique-ibs.net/media/uploads/vignettes/_licence-pro.jpg" },
    // Sub-programs for "VAE / VAP"
    { parentId: mainPrograms.find(p => p.name === "VAE / VAP")?.id, order: 1, name: "Licence", slug: "licence", cover: "https://www.atlantique-ibs.net/media/uploads/programmes/vignette-landing-page_nY5ySsK.jpg" },
  ]);

  console.log("✅ Programs data migration completed successfully!");
  } catch (error) {
    console.error("Error during migration of programs data:", error);
    throw error;
  }
}